### ISSUE TITLE
Incorrect amounts can be sent on X Chain send page

### ISSUE THREAD

**Issue by ssg** [ava-labs/avalanche-wallet#102]
The amount to send is `0` by default on the send page for X chain. When you click the amount field and type your amount, say `1`, the input becomes `10` instead of `1` replacing `0`. That can make people transfer wrong amounts, causing loss of funds. This can be fixed by making the input field have the existing amount selected when focused. Currently the cursor is placed on the left of initial `0`.

The problem doesn't exist on C chain's amount input, only on X chain's input.

**Comment by kanatliemre** [comment]
Should be fixed now, thanks
