### ISSUE TITLE
Cross-chain transaction anomaly

### ISSUE THREAD

**Issue by andriytyurnikov** [ava-labs/avalanche-wallet#111]
Hello. I observe anomaly with CrossChain transaction - not MetaMask, not web wallet display balance on C-Chain.
I hope it is not another client bug.

https://explorer.avax.network/tx/7ebRaY1FK2DzWbo2jxRQDvdKC5YrRddT8JETBgigEJeEb5D6P

**Comment by kanatliemre** [comment]
Hello. Can you please explain the anomaly you are observing?

**Comment by andriytyurnikov** [comment]
@kanatliemre oh, yes, sorry - so expected result of this cross-chain transaction is to have additional +48.289000000 AVAX on AVAX-C account 0x268Db4CDBea3966885f0EBAF9400ee81949120c2
But not MetaMask not your wallet display this expected AVAX-C balance. Perhaps it is not a wallet issue but RPC issue or client issue, I am not sure where to report this problem.

**Comment by kanatliemre** [comment]
It is possible that the AVAX you exported did not import successfully. Can you try going to Advanced page and clicking "Import C"

**Comment by andriytyurnikov** [comment]
@kanatliemre Thanks! It worked.
