### ISSUE TITLE
Deprecated API usage warnings

### ISSUE THREAD

**Issue by aanupam23** [ava-labs/avalanche-wallet#14]
**Warning Messages**
Logging using a Private key on the Wallet site shows the following warnings on Developer Console.
```
Deprecated API usage: PDFDocumentLoadingTask.then method, use the `promise` getter instead
Deprecated API usage: RenderTask.then method, use the `promise` getter instead.
```

**Information**
This issue is related to accessing the wallet using the private keys.

**Comment by kanatliemre** [comment]
No longer using the PDF library.
