### ISSUE TITLE
Possible Denial of service 

### ISSUE THREAD

**Issue by Shashank-In** [ava-labs/avalanche-wallet#17]
https://github.com/ava-labs/ava-wallet/blob/master/src/store/modules/assets/assets.ts

Request 

```
POST /ext/bc/avm HTTP/1.1
Host: bootstrap.ava.network:21000
User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:76.0) Gecko/20100101 Firefox/76.0
Accept: application/json, text/plain, */*
Accept-Language: en-GB,en;q=0.5
Accept-Encoding: gzip, deflate
Content-Type: application/json;charset=UTF-8
Content-Length: 193
Origin: https://wallet.ava.network
Connection: close
Referer: https://wallet.ava.network/wallet/send

{"id":3,"method":"avm.getUTXOs","params":{"addresses":["X-ABmnPvGQBd81cHyWFeJfzuoFz7rGwAqPR",
"X-AJPWXendnHJJoapqs81GMvJNDcYLVSngv",
"X-AJPWXendnHJJoapqs81GMvJNDcYLVSngv"
]},"jsonrpc":"2.0"
```

Response 

```
HTTP/1.1 200 OK
Access-Control-Allow-Origin: *
Content-Type: application/json; charset=utf-8
Vary: Origin
X-Content-Type-Options: nosniff
Date: Tue, 26 May 2020 16:56:21 GMT
Content-Length: 213
Connection: close

{"jsonrpc":"2.0","result":{"utxos":["9mJg6mV6XKTtZSjbMxP7TWVBvDpqAYTbXsUnhwScQt5u8aN1cup4AbgPgVT5jVPqoXJJwuWDfn9DJ9y9JiE1uGvd4m1brS4hrimV2voHb6JPYVnBVHa14Sm5UKmbgDwgYLPNo441hxwSXJECWBGq8cEe4m4LGBVtwaZx"]},"id":3}
```

The wallet checks for `UTXO` and the addresses are passed via an array. The array has no restrictions on how many addresses can be passed. If tens of thousands of addresses are passed through the wallet service, it can cause stress on the node. 

This is a potential security issue. 
Let me know what everyone thinks.

**Comment by kanatliemre** [comment]
Shouldn't this sort of vulnerabilities get handled at the server level? Anyone outside the wallet can make such a request.

**Comment by collincusce** [comment]
This does sound like more of a node-level validation issue on github.com/ava-labs/gecko

**Comment by Shashank-In** [comment]
Mostly everyone uses the same code. I think this should be patched at the node level as well.
