### ISSUE TITLE
Wallet needs an "ASAP" setting for start of staking period

### ISSUE THREAD

**Issue by jzu** [ava-labs/avalanche-wallet#62]
After having set all parameters for the staking period, I got an error because the Start Date and Time field was invalid. That's probably because I carefully reviewed the transaction before hitting the Confirm button… and the set time was already in the past. I had to redo everything with time set to a few minutes later, and everything went fine.

Would it be possible to have an [ASAP] option in order to improve the UX?

Also, I've been told of at least 2 (maybe related) strange issues on the Avalanche-Francophone Telegram. These times, the transactions gave a green light and a txid for a validator and a delegator respectively - but nothing appeared on the explorer or vscout, and the funds were still available. Redoing the transactions worked ok. This didn't happen to me, but I can get more info if needed.

**Comment by kanatliemre** [comment]
Wallet defaults to 5 minutes from form submission now.
