### ISSUE TITLE
Fuji testnet tx links incorrectly directed to mainnet explorer

### ISSUE THREAD

**Issue by michaelbnewman** [ava-labs/avalanche-wallet#64]
When using the wallet with the Fuji testnet, transactions listed are incorrectly directed to the [mainnet explorer](https://explorer.avax.network/) rather than the [testnet explorer](https://explorer.avax-test.network/).

**Comment by kanatliemre** [comment]
Yes noticed too. Will fix soon!

**Comment by kanatliemre** [comment]
Fixed.
