### ISSUE TITLE
WebWallet could not handle correctly addresses with more than 1024 UTXO

### ISSUE THREAD

**Issue by fenicks** [ava-labs/avalanche-wallet#66]
After reaching more than 1024 UTXO, the wallet balance is not working correctly and NFT is not displayed.
This is related to this issue: https://github.com/ava-labs/avalanchego/issues/524

**Comment by kanatliemre** [comment]
I believe this is on the X chain. Fix will be up soon.

**Comment by fenicks** [comment]
> I believe this is on the X chain. Fix will be up soon.

Yes it's on X-Chain but limitation of 1024 UTXO existon P-Chain too.

**Comment by kanatliemre** [comment]
this issue shouldn't exist on the P chain, but I'll have another look

**Comment by fenicks** [comment]
Not sure but in https://github.com/ava-labs/avalanchego/blob/master/vms/platformvm/service.go#L368 in this case https://github.com/ava-labs/avalanchego/blob/master/vms/platformvm/service.go#L429.

But I didn't inspect which case is suitable for the wallet regarding the P-Chain.

**Comment by kanatliemre** [comment]
Yep, absolutely! will push a fix for this tomorrow, let me know if it still persists.

**Comment by fenicks** [comment]
The problem is solve on Web wallet.
Thank you.
