### ISSUE TITLE
Have explorer URL be specific to the environment

### ISSUE THREAD

**Issue by cgcardona** [ava-labs/avalanche-wallet#69]
Currently the wallet's `tx_history_row` only creates explorer urls which point to the mainnet explorer. 

Dynamically create urls based on the environment. For mainnet txs then link to the [mainnet explorer](https://explorer.avax.network). For fuji txs then link to the [fuji explorer](https://explorer.avax-test.network)

Here's the location in the code: https://github.com/ava-labs/avalanche-wallet/blob/e099041c48a0eb24234fcfff59486e8893c22b1d/src/components/SidePanels/TxHistoryRow.vue#L44-L47

**Comment by kanatliemre** [comment]
This is fixed with the recent updates.
