### ISSUE TITLE
CORS limitations on https://explorerapi.avax.network/ 

### ISSUE THREAD

**Issue by sponnet** [ava-labs/avalanche-wallet#70]
When I host the wallet locally - it cannot connect to `https://explorerapi.avax.network/` because of a CORS error

```
Access to XMLHttpRequest at 'https://explorerapi.avax.network/....` from origin
'http://my.avalanchego.avado.dnp.dappnode.eth' has been blocked by CORS policy: 
No 'Access-Control-Allow-Origin' header is present on the requested resource.
```

Is there any chance to remove CORS checking on that host from your side so that we can connect to it ?

**Comment by kanatliemre** [comment]
Can you share the full url you are requesting.

**Comment by kanatliemre** [comment]
Are you still seeing this issue?

**Comment by kanatliemre** [comment]
This issue is resolved.
