### ISSUE TITLE
Error exporting wallet to keyfile

### ISSUE THREAD

**Issue by sponnet** [ava-labs/avalanche-wallet#71]
## Description

When opening a wallet from a mnemonic phrase and then trying to export the wallet to a keyfile 
( Manage -> export keys ) throws a JavaScript error in the console:

```
Uncaught (in promise) TypeError: Cannot read property 'importKey' of undefined
    at t.<anonymous> (Crypto.ts:40)
    at u (tslib.es6.js:100)
    at Object.next (tslib.es6.js:81)
    at tslib.es6.js:74
    at new Promise (<anonymous>)
    at o (tslib.es6.js:70)
    at t._keyMaterial (app~21833f8f.0185275a.js:1)
    at t.<anonymous> (Crypto.ts:142)
    at u (tslib.es6.js:100)
    at Object.next (tslib.es6.js:81)
```

## Steps to reproduce

- open wallet home screen
- select "Access Wallet"
- select "Mnemonic Key Phrase"
- paste your mnemonic 
- click "access wallet"
- on the wallet home screen select Manage->Export Keys
- type any password
- press the "Export Wallet" button

**Comment by kanatliemre** [comment]
I am not able to replicate this issue, export works fine on my end. What browser are you using?

**Comment by sponnet** [comment]
I'm using latest chrome - maybe it's due to the local build of the wallet,
although I'm using the instructions as described. I will double check.

**Comment by kanatliemre** [comment]
If its a local build make sure its served over https.

**Comment by sponnet** [comment]
Not using HTTPS was indeed the culprit.
