### ISSUE TITLE
Assets and balance disappering from node wallet

### ISSUE THREAD

**Issue by mahofmahof** [ava-labs/avalanche-wallet#73]
I created assets and nfts from the wallet at my nod,now i cannot see them when i try get all balances:: 
curl -X POST --data '{
    "jsonrpc":"2.0",
    "id"     : 1,
    "method" :"avm.getAllBalances",
    "params" :{
        "address":"X-avax1n9fvwa976dqjz9ypytw7hpvqywc8ue8x6dzjls"
    }
}' -H 'content-type:application/json;' 127.0.0.1:9650/ext/bc/X
{"jsonrpc":"2.0","result":{"balances":[{"asset":"2Kry7Gn8AJTmbMeWuQdGLUwdhzj3g8VCG6KLMB7eg4AbNVHXN2","balance":"19051905"},{"asset":"64hgTXXSDNaaeQFsjZZWXWmVNKJmJHTMrhSZgoATyGhwsupDc","balance":"19029990"}]},"id":1}

but from explorer i can see them there are 16 assets: https://explorer.avax.network/address/X-avax1n9fvwa976dqjz9ypytw7hpvqywc8ue8x6dzjls

and also at the last situation i sent 1 avax to this wallet minted 2 nfts from node balance is 0 but from explorer 0.002 fee is burned and there is 5.8 avax https://explorer.avax.network/address/X-avax1n9fvwa976dqjz9ypytw7hpvqywc8ue8x6dzjls 
my node version is avalanche/1.0.4 [network=mainnet, database=v1.0.0, commit=032a79a3dcb928f7bc0fcac7f30ed13ab6e7aae6]

**Comment by kanatliemre** [comment]
Are you seeing the issues on your node, or the web wallet?

**Comment by mahofmahof** [comment]
on the wallet but wallet is on the node, then where should i ask this issue

**Comment by kanatliemre** [comment]
@mahofmahof Please post at he node repository @ava-labs/avalanchego

**Comment by mahofmahof** [comment]
ok
