### ISSUE TITLE
P and X address switched

### ISSUE THREAD

**Issue by tuloski** [ava-labs/avalanche-wallet#84]
I must admit that I'm very new to avalance, so it might be correct, but to me it seemed weird.
I logged in the wallet using ledger hardware wallet. I was presented an X and a P address, let's call it X-ABC and P-DEF.
Next time I logged in, they were switched, i.e. it was X-DEF and P-ABC.
Is it correct?

**Comment by kanatliemre** [comment]
Are you using the web wallet connected to the mainnet nodes, or are you connecting to your own node?

X and P addresses share the same address space so they can be the same and thats perfectly normal. It would be weird if they switched like you said. What could have happened is X-ABC became X-DEF and P-DEF became something else, or vice versa.

**Comment by tuloski** [comment]
Web wallet connected to mainnet. Not my own node.
I didn't get what could happen. So if X-ABC became X-DEF and P-DEF became P-GHJ is ok?

**Comment by kanatliemre** [comment]
Yes, it has to do with how HD wallet works. Your wallet has infinite amount of addresses it can use and it starts with the first one. Once that address receives a transaction it uses the next one and so on, so it can look like this:

1) X-ABC
2) X-DEF
3) X-GHJ

same for P since they share the same address space

1) P-ABC
2) P-DEF
3) P-GHJ

**Comment by tuloski** [comment]
But the first address I got were different. They weren't X-ABC and P-ABC, they were already different like X-ABC and P-DEF.
Moreover can I still use the first X-ABC all the time?
All this is a bit weird and confusing for noobs like me.

**Comment by kanatliemre** [comment]
They could be different if you already used the 1st P address. You can go to Manage > HD Addresses to see these addresses.

And yes previous addresses are still valid. HD Wallets are a weird concept and its definitely confusing.

**Comment by tuloski** [comment]
Thanks for the explaination. I'll dig deeper into avalanche technical stuff soon.
Closing.
