### ISSUE TITLE
Cross chain transfer failed, AVAX disappeared

### ISSUE THREAD

**Issue by tuloski** [ava-labs/avalanche-wallet#88]
I did a crosschain transfer from P TO X using ledger hardware wallet.
An error occurred (which unfortunately I didn't write down).
Now the 35 AVAX of the transaction disappeared. But if I check in avax explorer with the x-address I see 2 identical address, one with 0 AVAX and the other with the 35 AVAX missing. If I click on the address it loads forever (in the explorer). No transactions shown.

The only transaction I see on the wallet is this (some data hidden for privacy):
Transaction Details
ID  So1Q6cUm8aXUZuafDQ21nLRjXXXX
Status Success
Timestamp 23 minutes ago (2/8/2021, 6:20:45 PM)
Value 38.805515662 AVAX
Type PVM Export
Transaction Fee 0.001 AVAX
Text hex 00000000 UTF-8 
Asset Type Fixed Cap
Input UTXOs
Tx 
pFMRwHSDi1SzogMfxrf9h2v2akRntpSFWxxxxx
Lock Time 0
Threshold 1
From X-avax15uhmn7gyynjhw32XXXX
Type Transferable
Amount 37.288400000 AVAX

226uvuVeuam59CezCZkLvxxxxxxxxxxxx
Lock Time 0
Threshold 0
1.518115662 AVAX

Output UTXOs
Tx -
Lock Time 0
Threshold 1
To X-avax1gx5vlnkhudu9dxxxxxx
Type Transferable 
Amount 3.804515662 AVAX

To X-avax1wsl2ms797zrfkvxxxxxx
Type Transferable
Amount 35.001000000 AVAX

Sorry for the bad formatting.
Why are there weird amounts? 38, 3.8, 1.5?

What is going on here and why everything is so complex with AVAX? It's definitely not user friendly.

**Comment by kanatliemre** [comment]
Hello, your import transaction probably failed. If you go to Advanced page and click Import to X it should retrigger an import and your funds should appear after refreshing your balance.

You should checkout our discord, there are many people over there that can help with issues you might run into.
https://discord.com/invite/RwXY7P6

**Comment by tuloski** [comment]
Many thanks!
It worked. So as suggestion I'd point the users to that in the wallet whenever a cross chain transaction fails.
Something like if it fails a popup appears saying: "Uh-oh, it seems your transaction failed, if the funds seems disappeared try in advanced->....".

**Comment by smfd4ever** [comment]
I log in using my ledger on the AVAX wallet and transfer from x-chain to the c-chain but then the funds didnt show up to my c-chain. I went to advance tab and click import c it did import but still didnt see the fund showing up in my c-chain... help??? i am also confuse.

**Comment by effusion** [comment]
I just faced the same issue. I tried to transfer between the x and the c chain. The export got stuck. The amount is still present but does not show up in the c-chain.
