### ISSUE TITLE
No option to transfer to C-Chain

### ISSUE THREAD

**Issue by tuloski** [ava-labs/avalanche-wallet#93]
I'm trying to to a cross chain transfer from X or P chains to C-Chain.
In the Cross chain tab the only options I see are from P to X and vice versa. No options for C chain.
I followed the documentation here https://docs.avax.network/build/tutorials/platform/transfer-avax-between-x-chain-and-c-chain without success.

**Comment by tuloski** [comment]
"Solved". Using hardware ledger the transfer to C chain doesn't seem implemented yet.
I'll leave the issue open because maybe implementing a simple message for the users using hardware wallets would be nice. Something like leaving the option to select C-chain as destination, but if selected (while using hardware wallet) a warning is displayed.

**Comment by kanatliemre** [comment]
This is supported on the beta wallet now. Closing.
